apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "overlord.fullname" . }}
  labels:
    {{- include "overlord.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "overlord.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "overlord.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: OVERLORD_APP_NAME
              value: {{ .Values.env.OVERLORD_APP_NAME | quote }}
            - name: OVERLORD_DATA_DIR
              value: {{ .Values.env.OVERLORD_DATA_DIR | quote }}
            - name: OVERLORD_DEFAULT_ENVIRONMENT
              value: {{ .Values.env.OVERLORD_DEFAULT_ENVIRONMENT | quote }}
            - name: OVERLORD_DEFAULT_WORKSPACE
              value: {{ .Values.env.OVERLORD_DEFAULT_WORKSPACE | quote }}
            - name: HOST
              value: {{ .Values.env.HOST | quote }}
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          {{- if .Values.storage.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "overlord.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

